--TBLHAREKET tablosunda yer alan ürün adýný, müþteri ve personel ad soyadlarýný getiren sorgu
--Prosedür üzerinden uygulama iþlemi
CREATE PROCEDURE PROJE10
AS
SELECT HAREKETID,URUNAD,(AD + ' ' + SOYAD) AS 'MÜÞTERÝ', TBLPERSONEL.ADSOYAD, TBLHAREKET.FIYAT FROM TBLHAREKET
INNER JOIN TBLURUNLER ON TBLURUNLER.URUNID = TBLHAREKET.URUN
INNER JOIN TBLMUSTERI ON TBLMUSTERI.ID = TBLHAREKET.MUSTERI
INNER JOIN TBLPERSONEL ON TBLPERSONEL.ID = TBLHAREKET.PERSONEL