--CREATE PROCEDURE ETUT
--AS
SELECT ID,DERSAD,(TBLOGRETMEN.AD + ' ' + TBLOGRETMEN.SOYAD) AS 'Öðretmen',
TARIH, SAAT, DURUM
FROM TBLETUT
INNER JOIN TBLDERSLER ON TBLETUT.DERSID = TBLDERSLER.DERSID
INNER JOIN TBLOGRETMEN ON TBLETUT.OGRETMENID = TBLOGRETMEN.OGRTID
