--TBLHAREKETLER tablosunda yer alan ürünün isimlerini gösteren sorgu
--SELECT AD FROM TBLHAREKETLER
--INNER JOIN TBLURUNLER
--ON TBLURUNLER.ID = TBLHAREKETLER.URUN

--TBLHAREKETLER tablosunda yer alan ürünün isimlerini ve müþterilerin isimlerini gösteren sorgu
--SELECT AD, ADSOYAD FROM TBLHAREKETLER
--INNER JOIN TBLURUNLER
--ON TBLURUNLER.ID = TBLHAREKETLER.URUN
--INNER JOIN TBLMUSTERILER
--ON TBLMUSTERILER.ID = TBLHAREKETLER.MUSTERI

--TBLHAREKETLER tablosunda yer alan ürünün isimlerini, müþterilerin isimlerini ve personellerin isimlerini gösteren sorgu
--SELECT TBLURUNLER.AD, ADSOYAD, TBLPERSONELLER.AD, FIYAT FROM TBLHAREKETLER
--INNER JOIN TBLURUNLER
--ON TBLURUNLER.ID = TBLHAREKETLER.URUN
--INNER JOIN TBLMUSTERILER
--ON TBLMUSTERILER.ID = TBLHAREKETLER.MUSTERI
--INNER JOIN TBLPERSONELLER
--ON TBLPERSONELLER.ID = TBLHAREKETLER.PERSONEL

--TBLHAREKETLER tablosunda yer alan ürünün isimlerini, müþterilerin isimlerini ve personellerin isimlerini gösteren sorguyu prosedür olarak oluþturma
CREATE PROCEDURE PROJE6
AS
SELECT TBLURUNLER.AD, ADSOYAD, TBLPERSONELLER.AD, FIYAT FROM TBLHAREKETLER
INNER JOIN TBLURUNLER
ON TBLURUNLER.ID = TBLHAREKETLER.URUN
INNER JOIN TBLMUSTERILER
ON TBLMUSTERILER.ID = TBLHAREKETLER.MUSTERI
INNER JOIN TBLPERSONELLER
ON TBLPERSONELLER.ID = TBLHAREKETLER.PERSONEL